---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker image
      docker_image:
        name: vineepinee/calculator:latest
        source: pull

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Run Docker container
      shell: docker run -it -d --name Calculator vineepinee/calculator:latest
